# Navigation Links
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: About
    url: /about/
    weight: 20
  - name: Now
    url: /now/
    weight: 30
  - name: Books
    url: /books/
    weight: 40
  - name: Blog
    url: /blog/
    weight: 50
  - name: Uses
    url: /uses/
    weight: 60


