# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# This file is formatted using YAML syntax - learn more at https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  mode: system
  color: blue

# SEO
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: 'Chia-Lun (Charles) Tsai'
    description: "Chia-Lun is an incoming Master of Computer Science student at UIUC, with a Bachelor's in Computer Science from National Yang Ming Chiao Tung University, Taiwan. Chia-Lun also spent time as an exchange student at Chalmers University of Technology in Sweden. Chia-Lun has industry experience as an intern at NVIDIA, where he worked on GPU firmware testing and fuzzing. His skills include C, C++, Python and Go programming language, and he is passionate about solving complex problems through technology. Chia-Lun is eager to connect with professionals in the tech community and explore new opportunities in computer science."
    twitter: ''
  analytics:
    google_analytics: 'G-0YVYNSM8WB'
    baidu_tongji: ''
    plausible: ''
    fathom: ''
    pirsch: ''
  verification:
    google: "cz_RUyCZ8LvzCP4jM2GfBDFP6d9cATt-XVM50HhkchY"
    baidu: ''

# Site header
header:
  navbar:
    enable: true
    show_search: true
    show_theme_chooser: false

# Site footer
footer:
  copyright:
    notice: '© {year} Chia-Lun Tsai. This work is licensed under {license}'
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Localization
locale:
  date_format: 'Jan 2, 2006'
  time_format: '3:04 PM'

# Site features
features:
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: 'https://github.com/soulrrrrr/soulrrrrr.github.io/'
    content_dir: content
    branch: main
